### PR TITLE
Added basemap import test

### PR DESCRIPTION
**Pull request by jgliss**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jgliss** [comment]
@conda-forge-admin, please rerender

**Comment by jgliss** [comment]
@conda-forge/staged-recipes, @ocefpaf  My tests fail due to the [well known basemap import problem](https://github.com/matplotlib/basemap/issues/419) related to ```KeyError 'PROJ_LIB'```, i.e. when running the docker build, it crashes  on my newly inserted basemap import check in test section of meta.yaml:
```
+ python -c 'from mpl_toolkits.basemap import Basemap'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conda/feedstock_root/build_artifacts/geonum_1558516567768/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 155, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/home/conda/feedstock_root/build_artifacts/geonum_1558516567768/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```
I am not sure if it is really an environment problem, since I also tried to install (the currently distributed geonum, build no. 2) into a new, empty environment:

```
conda create -n geonum python=3.7
conda activate geonum
conda install -c conda-forge geonum
python -c "from mpl_toolkits.basemap import Basemap"
```
which outputs:
```
(geonum) C:\Users\Jonas\Jonas\repos\geonum>python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonas\Anaconda3\envs\geonum\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jonas\\Anaconda3\\envs\\geonum\\Library\\share\\proj\\epsg'
```
I would appreciate suggestions how to fix this. Thanks in advance.

**Comment by ocefpaf** [comment]
`Basemap` is still using the old `proj4 5.2.0` and `pyproj 1.9.6`, nothing changed with the environmental variable there in a while :-/

Your example,

```
conda create -n geonum python=3.7
conda activate geonum
conda install -c conda-forge geonum
python -c "from mpl_toolkits.basemap import Basemap"
echo $PROJ_LIB
~/miniconda3/envs/TEST/share/proj
```

installs after activation of the environment. That only works with newer versions of conda. (Not exactly sure when that feature was added.)

The "old way" is to install and then activate:

```
conda create --name TEST geonum
conda activate TEST
python -c "from mpl_toolkits.basemap import Basemap"
echo $PROJ_LIB
~/miniconda3/envs/TEST/share/proj
```


Both works for me on Linux (I'll test Windows later today). Here is my `conda info -a` (not the conda and conda-build versions there):

```
     active environment : None
            shell level : 0
       user config file : /home/filipe/.condarc
 populated config files : /home/filipe/.condarc
          conda version : 4.6.14
    conda-build version : 3.18.1
         python version : 3.7.1.final.0
       base environment : /home/filipe/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/filipe/miniconda3/pkgs
                          /home/filipe/.conda/pkgs
       envs directories : /home/filipe/miniconda3/envs
                          /home/filipe/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.7.1 Linux/4.4.179-99-default opensuse/42.3 glibc/2.22
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

**Comment by jgliss** [comment]
Problem is registered in issue #6

**Comment by jgliss** [comment]
@ocefpaf Thanks for your hint, just tested on linux as well and it worked properly, like in your case. I have no idea what to do about the Windows issue, though...

Here is my `conda info -a` equivalent for linux:

```
     active environment : geonum
    active env location : /home/jonasg/anaconda3/envs/geonum
            shell level : 1
       user config file : /home/jonasg/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : /home/jonasg/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jonasg/anaconda3/pkgs
                          /home/jonasg/.conda/pkgs
       envs directories : /home/jonasg/anaconda3/envs
                          /home/jonasg/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Linux/4.15.0-47-generic ubuntu/16.04.5 glibc/2.23
                UID:GID : 421188:421188
             netrc file : None
           offline mode : False
```

**Comment by ocefpaf** [comment]
> Problem is registered in issue #6

In that issue you have a different problem (see my answer there).

Here you do get the right packages and the environment variable should be available during the test. May there was a regression on `conda-build`? Pinging @msarahan here for help.

**Comment by jgliss** [comment]
@ocefpaf seems like updating pyproj [conda-forge/pyproj-feedstock#40](https://github.com/conda-forge/pyproj-feedstock/pull/40) solved the issue in the checks here as well. Thanks!!!

**Pull request merged**
